### PR TITLE
Add support for target vectors in hybrid queries

### PR DESCRIPTION
**Pull request by joshdschneider**
Fixes [113](https://github.com/weaviate/typescript-client/issues/113).

### CODE REVIEW

**Comment by tsmith023** [comment]
Hi @joshdschneider, thanks for the PR on this one! Could you please add an integration test within the describe block [here](https://github.com/weaviate/typescript-client/blob/main/src/graphql/journey.test.ts#L2106) for your changes, cheers! 😁

**Comment by tsmith023** [comment]
@joshdschneider, your test fails (in quite an interesting way). It would seem that hybrid, due to its mixed nature as bm25 + vector search with the fusion algo, performs some cutoff returning only one result for you query!

**Comment by joshdschneider** [comment]
@tsmith023 ah, I see. Sorry about that—fixed!

**Review by tsmith023 — APPROVED** [review]
Thanks again!

**Pull request merged**
